### ISSUE TITLE
Missing arguments for send_unknown 

### ISSUE THREAD

**Issue by bozicm** [ffhs/moodle-local_nagios#1]
In https://github.com/ffhs/moodle-local_nagios/blob/master/cli/check.php#L120 and https://github.com/ffhs/moodle-local_nagios/blob/master/cli/check.php#L123 there are missing arguments, that create an exception when the result of the check is UNKNOWN.

**Comment by bozicm** [comment]
Hi, have you managed to look into the bug?

**Comment by adpe** [comment]
Hi @bozicm 

Thanks for this issue. Will have a look!

Greets
Adrian

**Comment by adpe** [comment]
I can't reproduce the bug, as per default the `$status` will always have `perfdata` set to 0. Can you please provide instructions how you manage to get a result object without `perfdata`?

Thanks @bozicm

**Comment by bozicm** [comment]
Hi, now I can't reproduce it either anymore. I'll just close this issue. Thanks!
